# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
#baseurl: ""                                # for local testing                 # CREATE.SH
baseurl: "/chassis"                         # for github pages the project name # CREATE.SH
#theme: bulma-clean-theme                   # for local testing                 # CREATE.SH
remote_theme: chrisrhymes/bulma-clean-theme # for github pages                  # CREATE.SH

plugins:
  - jekyll-feed
  - jekyll-remote-theme

title: chassis codegen
email: dirk.hoffmann.muc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chassis Kotlin Code Generator for Data-Transfer-Objects (DTO),
  using a flexible, concise and short kotlin DSL.
  Flexible create and copy their properties/field amongst each other, as well as
  RDBMS Mapping and fast CRUD operations using kotlinPoet and Jetbrains exposed DB Framework.
twitter_username: HoffiPivot
github_username:  HoffiMuc

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
